# Generated by Django 4.1.2 on 2022-10-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jatetxe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprice', models.FloatField()),
            ],
        ),
    ]
